routes.txt

Conflict with @NeoChen1024  Subnet, repair completed

fixed address by nextmoe_icecat

---

bgp-asn-next.txt
routes.txt

James58899 join network

---

asn/AS4201270005
asn/AS4201270008

modified:   asn/AS4201270008
by nextmoe-icecat

	modified:   asn/AS4201270005

---

README.md
docs/index.html

modified:   README.md
modified:   docs/index.html
Updated some information about ipv6 and updated the homepage by nextmoe_icecat

Updated some information about ipv6 and updated the homepage

---

route/10.127.0.24,30

modified:   route/10.127.0.24,30

fix name error x3 by nextmoe-boom

---

dns/db.10.127
dns/db.fd10.127

magicneko network add ipv4/6 rdns

---

dns/neonetwork

add DNS:
ipv4.tracker.neo
ipv6.tracker.neo
tracker.neo

DNS: tracker.neo

---

dns/db.10.127
node/MagicNeko.toml
peer/septs.toml
peer/staph.toml

1 Service node information change (RU node is removed, IP is diverted to JP02)
2 peer information changes
3 dns information change

MagicNeko unified change

---

asn/AS4201270008.toml
route/AS4201270005.toml
route/AS4201270008.toml
route/AS4201270017.toml

Add VPN segment, tunnel address segment, IX reserved segment
Automatically merge after waiting for the ROA generator to succeed

MagicNeko node update

---

asn/AS4242420308.toml
entity/VILLISEK.toml
node/VILLISEK.toml
route/AS4242420308.toml

Hello, 
I'm new aboard. I hope I didn't miss a file to create.

I join as AS4242420308

---

asn/AS4201270019.toml
document/asn-dir.txt
entity/Cupkappu.toml
node/Cupkappu.toml
route/AS4201270019.toml

Cupkappu 20201108/register as AS4201270019

---

asn/AS140913.toml
entity/magicneko.toml

Add ASN140913 
Modify information

Added MagicNeko other network data

---

dns/neonetwork

Reverts NeoCloud/NeoNetwork#146

Revert "Add kagl.neo"

---

asn/AS140913.toml
asn/AS141706.toml
route/AS141706.toml

MagicNeko ASN handover

---

dns/db.10.127
dns/neonetwork
dns/rfc2317.toml
node/iEdon.toml
route/AS4242422189.toml

Add new route record for new braches(super nodes)

Add new route record for new braches(super nodes)

---

dns/neonetwork
entity/Yura.toml
route/AS4242422464.toml

And add a supernet according to the requirements

register yura.neo

---

route/AS4242422464.toml

provide Anycast recursive dns in uncovered areas such as the US East

Announce NeoNetwork Anycast DNS

---

asn/AS141776.toml
asn/AS4201270017.toml
asn/AS4242420247.toml
entity/Ren Baoshuo.toml
route/AS141776.toml
route/AS4201270017.toml
route/AS4242420247.toml

+ AS141776
+ AS4201270017
+ AS4242420247
+ 10.127.60.0/24
+ fd10:127:9898::/48

Add: Baoshuo Network

---

asn/AS4242420288.toml
route/AS4242420288.toml

Allow DN42 AS4242420288 to announce my NeoNetwork prefixes and vice versa.
(See also https://git.dn42.dev/dn42/registry/pulls/883)

AS4201270030: Allow DN42 AS4242420288 origin

---

dns/db.10.127

fix lily.neo. PTR

---

dns/db.10.127
dns/db.fd10.127
dns/neonetwork

Signed-off-by: funnysyc <yc.s@outlook.com>

Update DNS for HuajiTech

---

asn/AS4242422923.toml
route/AS4242422923.toml

Signed-off-by: Marek Küthe <m.k@mk16.de>

allow my dn42 as to announce my neo ips as well

---

asn/AS4201270456.toml
asn/AS4201270458.toml
route/AS4201270456.toml
route/AS4201270458.toml

Signed-off-by: funnysyc <yc.s@outlook.com>

Change ASN from 4201270458 to 4201270456

---

asn/AS4201270456.toml
asn/AS4242420458.toml
asn/AS4242422458.toml
dns/db.10.127
dns/db.fd10.127
dns/neonetwork
dns/rfc2317.toml
entity/huajitech.toml
entity/ricky8955555.toml
route/AS4242420458.toml
route/AS4242422458.toml

Signed-off-by: funnysyc <yc.s@outlook.com>

Add organization HuajiTech

---

asn/AS4242422399.toml
entity/Qin Yuzhen.toml
route/AS4242422399.toml

Signed-off-by: YuzhenQin <1@jin-dan.site>

Add: QYZ Network

---

entity/mark22k.toml
route/AS4201272923.toml
route/AS4242422923.toml

Signed-off-by: Marek Küthe <m.k@mk16.de>
remove some contacts methods
Signed-off-by: Marek Küthe <m.k@mk16.de>

add max-len for my route objects

---

asn/AS211390.toml
entity/YuzhenQin.toml
route/AS211390.conf

Signed-off-by: GitHub <noreply@github.com>

Add Yuzhen Network

---

dns/neonetwork

Update name servers for iwarp.neo, yux.neo, and go.neo.

Update name servers

---

asn/AS4201270037.toml
dns/db.10.127
dns/db.fd10.127
dns/neonetwork
route/AS4201270037.toml

Signed-off-by: funnysyc <yc.s@outlook.com>

Add FUNNYSYC-AS

---

dns/db.10.127
dns/neonetwork

AS4242421181
Signed-off-by: ne-vlezay80 <ne-vlezay80@yandex.ru>

Register nevlezay.neo and create reverse dns from 10.127.192.0/24

---

asn/AS4201272032.toml
dns/db.10.127
dns/db.fd10.127
dns/neonetwork
entity/Razuritta.toml
route/AS4201272032.toml

request add lapisnet-neo

---

asn/AS4201270036.toml
route/AS4201270036.toml

Register New ASN For IX36

---

asn/AS4242420803.toml
entity/Yukari.toml
route/AS207268.toml
route/AS4242420803.toml

- Fix telegram contact info
- Return unused IPv6 address
- Reassign IPv4 address to AS4242420803, with authorization from @billchenchina

reassign ipv4 resources to AS4242420803

---

asn/AS4201270003.toml
entity/stone.toml
route/AS4201270003.toml

This is an entry that I create as part of my registration proxy service.
Stone emailed me and told me that he didn't want a GitHub account. So I'm creating the entry for him.

Register stone

---

asn/AS4201273751.toml
dns/db.10.127
dns/db.fd10.127
dns/neonetwork
entity/InPRTx.toml
route/AS4201273751.toml

Revert "Add AS4201273751"
